spring:
  application:
    name: restaurante
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restauranteDB
    #url: jdbc:h2:file:/data/restauranteDB
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        open-in-view: true

logging:
  level:
    #root: TRACE
    #root: DEBUG
    #root: INFO
    root: WARN
    #root: ERROR
  file:
    name: log/restaurante.log
    path: /log